DmrbTakip/Controllers/KategorisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DmrbTakip.DAL;

namespace DmrbTakip.Controllers
{
    [Authorize]
    public class KategorisController : Controller
    {
        DemirbasDBEntities db;
        public KategorisController(DemirbasDBEntities _db)
        {
            db = _db;
        }

        public async Task<ActionResult> Index()
        {
            return View(await db.Kategoris.ToListAsync());
        }


        public ActionResult Create()
        {
            return View();
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Kategoris.Add(kategori);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(kategori);
        }

      
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = await db.Kategoris.FindAsync(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,kategoriAdi,durum")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategori).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(kategori);
        }
        
    }
}

DmrbTakip/Views/Kategoris/Create.cshtml
@model DmrbTakip.DAL.Kategori

@{
    ViewBag.Title = "kategoriler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Yeni Kategori Tanımlama</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Ana Sayfa</a></li>
                            <li><a href="@Url.Action("Index","Kategoris")">Kategoriler</a></li>
                            <li>Yeni Kategori Tanımlama</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="page-box">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Kategori</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.kategoriadi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input name="kategoriadi" type="text" class="form-control" value="" required/>
                        @*@Html.EditorFor(model => model.kategoriadi, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.ValidationMessageFor(model => model.kategoriadi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.durum, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="form-group form-checkbox">
                            <input type="checkbox" checked="checked" name="durum" id="durum" value="1">
                            <label class="inline control-label" for="durum">Aktif / Pasif</label>
                        </div>                      
                        @Html.ValidationMessageFor(model => model.durum, "", new { @class = "text-danger" })
                    </div>
                </div>
               
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kaydet" class="btn btn-success" />
                    </div>
                </div>
            </div>
            }

            <div>
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

DmrbTakip/Views/Kategoris/Delete.cshtml
@model DmrbTakip.DAL.Kategori

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kategori</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.kategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.durum)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DmrbTakip/Views/Kategoris/Edit.cshtml
@model DmrbTakip.DAL.Kategori

@{
    ViewBag.Title = "kategoriler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Kategori Güncelleme</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Ana Sayfa</a></li>
                            <li><a href="@Url.Action("Index","Kategoris")">Kategoriler</a></li>
                            <li>Kategori Güncelleme</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="page-box">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Kategori</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.kategoriadi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input name="kategoriadi" type="text" class="form-control" value="@Model.kategoriadi" required />                          
                            @Html.ValidationMessageFor(model => model.kategoriadi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.durum, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-group form-checkbox">
                                <input type="checkbox" @(Model.durum == 1 ? "checked": "") name="durum" id="durum" value="1">
                                <label class="inline control-label" for="durum">Aktif / Pasif</label>
                            </div>
                            @Html.ValidationMessageFor(model => model.durum, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Güncelle" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

DmrbTakip/Views/Kategoris/Index.cshtml
@model IEnumerable<DmrbTakip.DAL.Kategori>

@{
    ViewBag.Title = "kategoriler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Tanımlı Kategoriler</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Giriş</a></li>
                            <li>Tanımlamalar</li>
                            <li>Kategoriler</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcromb Row -->
<!-- Advance Table Row Start -->
<div class="row">
    <div class="col-md-12">
        <div class="page-box">
            <div class="datatables-example-heading">
                <h3>Kategoriler</h3>
            </div>
            @Html.ActionLink("Yeni Kayıt", "Create", null, new { @class = "btn btn-info" })
            <div class="table-responsive advance-table">
                <table class="table display table-bordered" id="datalist">
                    <thead>
                        <tr>
                            <th>
                               Kategori
                            </th>
                            <th>
                               Durum
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.kategoriadi)
                                </td>
                                <td>
                                    <input type="checkbox" name="durum" value="@item.durum" @(item.durum == 1 ? "checked" : "") class="checkbox" disabled/>
                                </td>
                                <td>
                                    @Html.ActionLink("Güncelle", "Edit", new { id = item.id }, new { @class = "btn btn-warning" })                                                               
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $('#datalist').dataTable({
            "scrollY": "800px",
            "scrollCollapse": true,
            "paging": false
        });
    </script>

}