DmrbTakip/Controllers/KullanicisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DmrbTakip.DAL;

namespace DmrbTakip.Controllers
{
    [Authorize]
    public class KullanicisController : Controller
    {
        DemirbasDBEntities db;
        public KullanicisController(DemirbasDBEntities _db)
        {
            db = _db;
        }
        public async Task<ActionResult> Index()
        {
            var kullanicis = db.Kullanicis.Include(k => k.Rol);
            return View(await kullanicis.ToListAsync());
        }

     
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanici kullanici = await db.Kullanicis.FindAsync(id);
            if (kullanici == null)
            {
                return HttpNotFound();
            }
            return View(kullanici);
        }

       
        public ActionResult Create()
        {
            ViewBag.rol_id = new SelectList(db.Rols.Where(w => w.durum == 1), "id", "rol1");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,kullaniciAdi,sifre,tarih,durum,rol_id")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                db.Kullanicis.Add(kullanici);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.rol_id = new SelectList(db.Rols.Where(w => w.durum == 1), "id", "rol1", kullanici.rol_id);
            return View(kullanici);
        }

       
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanici kullanici = await db.Kullanicis.FindAsync(id);
            if (kullanici == null)
            {
                return HttpNotFound();
            }
            ViewBag.rol_id = new SelectList(db.Rols.Where(w=>w.durum == 1), "id", "rol1", kullanici.rol_id);
            return View(kullanici);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,kullaniciAdi,sifre,tarih,durum,rol_id")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kullanici).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.rol_id = new SelectList(db.Rols.Where(w => w.durum == 1), "id", "rol1", kullanici.rol_id);
            return View(kullanici);
        }

        
    }
}

DmrbTakip/Views/Kullanicis/Create.cshtml
@model DmrbTakip.DAL.Kullanici

@{
    ViewBag.Title = "kullaniciler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Yeni Kullanıcı Tanımlama</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Ana Sayfa</a></li>
                            <li><a href="@Url.Action("Index","Kullanicis")">Kullanıcır</a></li>
                            <li>Yeni Kullanıcı Tanımlama</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="page-box">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Kullanici</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.kullaniciadi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="kullaniciadi" name="kullaniciadi" type="text" class="form-control" value="" required />                       
                        @Html.ValidationMessageFor(model => model.kullaniciadi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="sifre" name="sifre" type="text" class="form-control" value="" required />  
                        @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="tarih" name="tarih" type="text" class="form-control" value="" required />                   
                        @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Rol, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("rol_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.rol_id, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.durum, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="form-group form-checkbox">
                            <input type="checkbox" checked="checked" name="durum" id="durum" value="1">
                            <label class="inline control-label" for="durum">Aktif / Pasif</label>
                        </div>
                        @Html.ValidationMessageFor(model => model.durum, "", new { @class = "text-danger" })
                    </div>
                </div>
               

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kaydet" class="btn btn-success" />
                    </div>
                </div>
            </div>
            }

            <div>
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

DmrbTakip/Views/Kullanicis/Delete.cshtml
@model DmrbTakip.DAL.Kullanici

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kullanici</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.kullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kullaniciAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rol.rol1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rol.rol1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DmrbTakip/Views/Kullanicis/Details.cshtml
@model DmrbTakip.DAL.Kullanici

@{
    ViewBag.Title = "kullaniciler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Kullanici</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.kullaniciadi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kullaniciadi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rol.rol1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rol.rol1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Güncelle", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
</p>

DmrbTakip/Views/Kullanicis/Edit.cshtml
@model DmrbTakip.DAL.Kullanici

@{
    ViewBag.Title = "kullaniciler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Kullanıcı Güncelleme</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Ana Sayfa</a></li>
                            <li><a href="@Url.Action("Index","Kullanicis")">Kullanıcılar</a></li>
                            <li>Kullanıcı Güncelleme</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="page-box">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Kullanici</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.kullaniciadi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input id="kullaniciadi" name="kullaniciadi" type="text" class="form-control" value="@Model.kullaniciadi" required />
                            @Html.ValidationMessageFor(model => model.kullaniciadi, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.sifre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input id="sifre" name="sifre" type="text" class="form-control" value="@Model.sifre" required />                    
                            @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.tarih, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input id="tarih" name="tarih" type="text" class="form-control" value="@Model.tarih" required />                           
                            @Html.ValidationMessageFor(model => model.tarih, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Rol, "Rol", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("rol_id", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.rol_id, "", new { @class = "text-danger" })
                        </div>
                    </div>    
                    <div class="form-group">
                        @Html.LabelFor(model => model.durum, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-group form-checkbox">
                                <input type="checkbox" @(Model.durum == 1 ? "checked" : "") name="durum" id="durum" value="1">
                                <label class="inline control-label" for="durum">Aktif / Pasif</label>
                            </div>
                            @Html.ValidationMessageFor(model => model.durum, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Güncelle" class="btn btn-warning" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

DmrbTakip/Views/Kullanicis/Index.cshtml
@model IEnumerable<DmrbTakip.DAL.Kullanici>

@{
    ViewBag.Title = "kullaniciler";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Tanımlı Kullanıcılar</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Giriş</a></li>
                            <li>Tanımlamalar</li>
                            <li>Kullanıcılar</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcromb Row -->
<!-- Advance Table Row Start -->
<div class="row">
    <div class="col-md-12">
        <div class="page-box">
            <div class="datatables-example-heading">
                <h3>Kullanıcılar</h3>
            </div>
            @Html.ActionLink("Yeni Kayıt", "Create", null, new { @class = "btn btn-info" })
            <div class="table-responsive advance-table">
                <table class="table display table-bordered" id="datalist">
                    <thead>
                        <tr>
                            <th>
                                Kullanıcı Adı
                            </th>
                            <th>
                               Şifre
                            </th>
                            <th>
                               Tarih
                            </th>
                            <th>
                                Rol
                            </th>
                            <th>
                               Durum
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.kullaniciadi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.sifre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tarih)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Rol.rol1)
                            </td>
                            <td>
                                <input type="checkbox" name="durum" value="@item.durum" @(item.durum == 1 ? "checked" : "") class="checkbox" disabled />
                            </td>
                            <td>
                                @Html.ActionLink("Düzenle", "Edit", new { id = item.id }, new { @class = "btn btn-warning" })
                                @*@Html.ActionLink("İçerik", "Details", new { id = item.id })*@

                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $('#datalist').dataTable({
            "scrollY": "800px",
            "scrollCollapse": true,
            "paging": false
        });
    </script>

}