DmrbTakip/Controllers/GirisController.cs
using DmrbTakip.Models.Interfaceses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DmrbTakip.DAL;
using DmrbTakip.Models.Contructers;
using System.Data.Entity;

namespace DmrbTakip.Controllers
{
    [Authorize]
    public class GirisController : Controller
    {
        private I_Helper _hlp;
        private I_Giris _grs;
        public GirisController(I_Helper hlp, I_Giris grs)
        {
            _hlp = hlp;
            _grs = grs;
        }

        // GET: Giris
        public async Task<ActionResult> Index()
        {   
            Tuple <int,int,int,int,int> sayilar = await _grs.GetCounts();
            int demirbasSayisi = sayilar.Item1;
            int zimmetSayisi = sayilar.Item2;
            int depoSayisi = sayilar.Item3;
            int islemlogsayi = sayilar.Item4;
            int hatalogsayi = sayilar.Item5;

            IList<Demirba> demirbasListe = await _grs.DemirbasListe().ToListAsync();
            IList<Model> modelListe = await _grs.ModelListe().ToListAsync();
            IList<Marka> markaListe = await _grs.MarkaListe().ToListAsync();
            IList<Kategori> kategoriListe = await _grs.KategoriListe().ToListAsync();


            IList<Zimmet> sonYapilanZimmetler = await _grs.SonYapilanZimmetler();
            IList<Islem_Log> sonAlinanIslemHatalar = await _grs.SonAlinanIslemLoglari();

            ViewBag.demirbasSayisi = demirbasSayisi;
            ViewBag.zimmetSayisi = zimmetSayisi;
            ViewBag.depoSayisi = depoSayisi;
            ViewBag.islemlogsayi = islemlogsayi;
            ViewBag.hatalogsayi = hatalogsayi;

            ViewData["demirbasListe"] = demirbasListe;
            ViewData["modelListe"] = modelListe;
            ViewData["markaListe"] = markaListe;
            ViewData["kategoriListe"] = kategoriListe;
            ViewData["sonYapilanZimmetler"] = sonYapilanZimmetler;
            ViewData["sonAlinanIslemHatalar"] = sonAlinanIslemHatalar;

            IList<DemirbasKullanimOranView> gelenORan = await _grs.ZimmetOranlama();
            ViewBag.Oran = gelenORan;

            Tuple<int, int> demirbasOran =await _grs.KullanimDemirbasOrani();
            ViewBag.DemirbasOran = demirbasOran;

            return View();
        }  
      
    }
}

DmrbTakip/Controllers/ZimmetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DmrbTakip.DAL;
using DmrbTakip.Models.Contructers;
using DmrbTakip.Models.Interfaceses;

namespace DmrbTakip.Controllers
{
    [Authorize]
    public class ZimmetsController : Controller
    {
        DemirbasDBEntities db;
        I_Giris grs;
        public ZimmetsController(DemirbasDBEntities _db, I_Giris _grs)
        {
            db = _db;
            grs = _grs;
        }

        public async Task<ActionResult> PersonelListe()
        {

            try
            {
                ViewBag.Personeller = await db.Zimmets.Where(r => r.durum == 1).GroupBy(r => new PersonelZimmetView
                {
                    personel_id = r.personel_id.Value,
                    ad = r.Personel.ad,
                    soyad = r.Personel.soyad,
                    resim = r.Personel.resim,
                    birimadi = r.Personel.Birim.birimadi,
                    kat = r.Personel.Birim.Kat.katadi,
                    bina = r.Personel.Birim.Bina.binaadi,
                    durum =  r.Personel.durum
                }).Select(q => new PersonelZimmetView
                {
                    personel_id = q.Key.personel_id,
                    ad = q.Key.ad,
                    soyad = q.Key.soyad,
                    resim = q.Key.resim,
                    birimadi = q.Key.birimadi,
                    kat = q.Key.kat,
                    bina = q.Key.bina,
                    durum = q.Key.durum
                }).ToListAsync();
            }
            catch 
            {
                ViewBag.Personeller = new List<PersonelZimmetView>();
            }
            
            var zimmets = db.Zimmets.Include(z => z.Demirba).Include(z => z.Personel).Where(r => r.durum == 1 && r.ofis_id == null && r.personel_id != null);
            return View(await zimmets.ToListAsync());
        }

        public async Task<ActionResult> OfisListe()
        {
            try
            {
                ViewBag.Ofisler = await db.Zimmets.Where(r => r.durum == 1).GroupBy(r => new OfisZimmetView
                {
                    ofis_id = r.ofis_id.Value,
                    ofisno = r.Ofi.ofisno,
                    kat = r.Ofi.Kat.katadi,
                    bina = r.Ofi.Bina.binaadi
                    //eposta = r.Ofi.eposta,
                    //telefon = r.Ofi.telefon

                }).Select(q => new OfisZimmetView
                {
                    ofis_id = q.Key.ofis_id,
                    ofisno = q.Key.ofisno,
                    kat = q.Key.kat,
                    bina = q.Key.bina
                    //eposta = q.Key.eposta,
                    //telefon = q.Key.telefon
                }).ToListAsync();
            }
            catch 
            {
                ViewBag.Ofisler = new List<OfisZimmetView>();
            }
            
            var zimmets = db.Zimmets.Include(z => z.Demirba).Include(z => z.Ofi).Where(r => r.durum == 1 && r.ofis_id != null && r.personel_id == null);
            return View(await zimmets.ToListAsync());
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zimmet zimmet = await db.Zimmets.FindAsync(id);
            if (zimmet == null)
            {
                return HttpNotFound();
            }
            return View(zimmet);
        }


        public async Task<ActionResult> Create()
        {
            ViewBag.kategori_id = await grs.KategoriListe().ToListAsync();
            ViewBag.birim_id = await grs.BirimListe();
            ViewBag.kat_id = await grs.KatListe();
            ViewBag.bina_id = await grs.BinaListe(true);
            return View();
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var zimmet = await db.Zimmets.Where(r => r.ofis_id == null && r.id == id.Value).FirstOrDefaultAsync();
            if (zimmet == null)
            {
                return HttpNotFound();
            }
            ViewBag.kategori_id = await grs.KategoriListe().ToListAsync();
            ViewBag.birim_id = await grs.BirimListe();
            ViewBag.kat_id = await grs.KatListe();
            ViewBag.bina_id = await grs.BinaListe(true);
            return View(zimmet);
        }

        public async Task<ActionResult> Ofis_Create()
        {
            ViewBag.kategori_id = await grs.KategoriListe().ToListAsync();
            ViewBag.kat_id = await grs.KatListe();
            ViewBag.bina_id = await grs.BinaListe(null);
            return View();
        }

        public async Task<ActionResult> Ofis_Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zimmet zimmet = await db.Zimmets.Where(r => r.personel_id == null && r.id == id.Value).FirstOrDefaultAsync();
            if (zimmet == null)
            {
                return HttpNotFound();
            }
            ViewBag.kategori_id = await grs.KategoriListe().ToListAsync();
            ViewBag.ofis_id = await grs.OfisKatListe(zimmet.Ofi.bina_id, zimmet.Ofi.kat_id);
            ViewBag.kat_id = await grs.KatListe();
            ViewBag.bina_id = await grs.BinaListe(null);
            return View(zimmet);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Zimmet zimmet)
        {
            string sonuc = string.Empty;
            try
            {
                db.Zimmets.Add(zimmet);
                int sonucx = await db.SaveChangesAsync();
                string durum = string.Empty;
                if (zimmet.personel_id == null)
                {
                    durum = "ofise";
                }
                else
                {
                    durum = "personele";
                }
                sonuc = sonucx == 1 ? "Zimmet seçili " + durum + " başarı ile yapıldı" : "Kayıt sırasında hata meydana geldi.";
                return Json(sonuc, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                sonuc = ex.Message;
                return Json(sonuc, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Zimmetiade(int id)
        {           
            var zimmet = db.Zimmets.Where(r => r.ofis_id == null && r.id == id).FirstOrDefault();
            zimmet.iadetarih = DateTime.Now;
            zimmet.durum = 0;
            int sonuc = db.SaveChanges();
            return Json(sonuc, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Zimmet zimmet, string tarihd, string iadetarihd)
        {
            string sonuc = string.Empty;
            zimmet.tarih = Convert.ToDateTime(tarihd);
            if (!string.IsNullOrEmpty(iadetarihd))
            {
                zimmet.iadetarih = Convert.ToDateTime(iadetarihd);
            }
           
            if (zimmet.durum == (int)Models.Enums.EnumHelp.Durum.pasif)
            {
                zimmet.iadetarih = DateTime.Now;
            }
           
            db.Entry(zimmet).State = EntityState.Modified;
            int sonucx = await db.SaveChangesAsync();
            sonuc = sonucx == 1 ? "Zimmet güncelleme işlemi başarı ile yapıldı" : "Güncelleme sırasında hata meydana geldi.";
            if (sonucx == 1)
            {
                return Json(sonuc, JsonRequestBehavior.AllowGet);
            }
            
            ViewBag.kategori_id = await grs.KategoriListe().ToListAsync();
            ViewBag.birim_id = await grs.BirimListe();
            ViewBag.kat_id = await grs.KatListe();
            ViewBag.bina_id = await grs.BinaListe(true);
            ViewBag.model_id = await grs.ModelListe().ToListAsync();
            return View(zimmet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Ofis_Edit(Zimmet zimmet)
        {
            string sonuc = string.Empty;
            if (zimmet.durum == (int)Models.Enums.EnumHelp.Durum.pasif)
            {
                zimmet.iadetarih = DateTime.Now;
            }
            db.Entry(zimmet).State = EntityState.Modified;
            int sonucx = await db.SaveChangesAsync();
            sonuc = sonucx == 1 ? "Zimmet güncelleme işlemi başarı ile yapıldı" : "Güncelleme sırasında hata meydana geldi.";
            if (sonucx == 1)
            {
                return Json(sonuc, JsonRequestBehavior.AllowGet);
            }

            ViewBag.kategori_id = await grs.KategoriListe().ToListAsync();
            ViewBag.birim_id = await grs.BirimListe();
            ViewBag.kat_id = await grs.KatListe();
            ViewBag.bina_id = await grs.BinaListe(true);
            ViewBag.model_id = await grs.ModelListe().ToListAsync();
            return View(zimmet);
        }

        public async Task<IList<DemirbasView>> ZimmetKontrol(int model_id)
        {
            var kontrol = await db.Demirbas.Where(e => e.durum == 1 && e.model_id == model_id && e.Zimmets.Where(q => q.iadetarih == null).Count() == 0).Select(w => new DemirbasView { id = w.id, demirbasAdi = w.demirbasadi, serino = w.serino }).ToListAsync();
            return kontrol;
        }

        public async Task<JsonResult> GetPersonels(int birim_id)
        {
            var data = db.Personels.Where(e => e.durum == 1 && e.birim_id == birim_id).Select(w => new PersonelListView { id = w.id, Adi = w.ad, Soyadi = w.soyad });

DmrbTakip/Views/Zimmets/Delete.cshtml
@model DmrbTakip.DAL.Zimmet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zimmet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iadeTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iadeTarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Demirba.demirbasAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Demirba.demirbasAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personel.ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personel.ad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DmrbTakip/Views/Zimmets/Details.cshtml
@model DmrbTakip.DAL.Zimmet

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Zimmet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iadeTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iadeTarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.durum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Demirba.demirbasAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Demirba.demirbasAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personel.ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personel.ad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Güncelle", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-default" })
</p>

DmrbTakip/Views/Zimmets/PersonelListe.cshtml
@model IEnumerable<DmrbTakip.DAL.Zimmet>

@{
    ViewBag.Title = "PersonelZimmmet";
    Layout = "~/Views/Shared/_LMaster.cshtml";
    var personeller = (List<DmrbTakip.Models.Contructers.PersonelZimmetView>)ViewBag.Personeller;
}

<div class="row">
    <div class="col-md-12">
        <div class="breadcromb-area">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-left">
                        <h3>Tanımlı Personel Zimmetler</h3>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="seipkon-breadcromb-right">
                        <ul>
                            <li><a href="/">Giriş</a></li>
                            <li>Zimmetler</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcromb Row -->
<!-- Advance Table Row Start -->
<div class="row">
    <div class="col-md-12">
        <div class="page-box">
            <div class="datatables-example-heading">
                <h3>Personel Zimmetler</h3>
            </div>
            @Html.ActionLink("Yeni Kayıt", "Create", null, new { @class = "btn btn-info" })
            <div class="table-responsive advance-table">
                <table class="table display table-bordered" id="datatable1" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                Personel Bilgi
                            </th>
                            <th>
                                Bina
                            </th>
                            <th>Kat</th>
                            <th>Birim Bilgi</th>
                            <th>Zimmet Bilgi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in personeller)
                        {
                            string resim = string.IsNullOrEmpty(item.resim) ? "resimyok.jpg" : item.resim;
                            <tr>
                                <td>
                                    <img src="~/Resimler/@(resim)" style="width:120px" /><br />
                                    @item.ad @item.soyad
                                </td>
                                <td>
                                    @item.bina
                                </td>
                                <td>
                                    @item.kat
                                </td>
                                <td>
                                    @item.birimadi<br />
                                    <label style="color:@(item.durum == 1 ? "" : "red")"> @(item.durum == 1 ? "Aktif Personel" : "Pasif!")</label>

                                </td>
                                <td>
                                    <table class="table">
                                        <tr>
                                            <th>Kategori</th>
                                            <th>Marka</th>
                                            <th>Model</th>
                                            <th>
                                                Demirbaş Bilgi
                                            </th>
                                            <th>
                                                Zimmet Tarihi
                                            </th>
                                            @*<th>
                                                    İade Tarihi (İade Edilmişse)
                                                </th>*@
                                            <th>
                                                Açıklama
                                            </th>
                                            @*<th>
                                                    Durum
                                                </th>*@

                                            <th></th>
                                        </tr>
                                        @foreach (var itemDty in Model.Where(r => r.personel_id == item.personel_id))
                                        {
                                            <tr>
                                                <td>@itemDty.Demirba.Model.Kategori.kategoriadi</td>
                                                <td>@itemDty.Demirba.Model.Marka.markaadi</td>
                                                <td>@itemDty.Demirba.Model.modeladi</td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => itemDty.Demirba.demirbasadi)<br />
                                                    @itemDty.Demirba.serino
                                                </td>
                                                <td>
                                                    @itemDty.tarih.ToShortDateString()
                                                </td>
                                                @*<td>
                                                        @(itemDty.iadetarih == null ? "Kullanımda" : itemDty.iadetarih.Value.ToShortDateString())
                                                    </td>*@
                                                <td>
                                                    @Html.DisplayFor(modelItem => itemDty.aciklama)
                                                </td>
                                                @*<td>
                                                        <input type="checkbox" name="durum" value="@itemDty.durum" @(itemDty.durum == 1 ? "checked" : "") class="checkbox" disabled />
                                                    </td>*@

                                                <td>
                                                    @Html.ActionLink("Günceller", "Edit", new { id = itemDty.id }, new { @class = "btn btn-bordered-warning" })
                                                    <button class="btn btn-danger" onclick="Iadeet(@itemDty.id);">İade</button>
                                                </td>
                                            </tr>
                                        }
                                    </table>
                                </td>
                                <td>
                                    <a href="~/PZimmet.html?id=@item.personel_id" title="Çıktı Döküm Al" class="btn btn-info" target="_blank">Çıktı Döküm Al</a>
                                </td>


                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        function Iadeet(id) {
            debugger
            swal({
                title: "Zimmet iadesi?",
                text: "Demirbaş personel zimmetinden iade alınacaktır. Eminmsiniz!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "EVET",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    url: '@Url.Action("Zimmetiade", "Zimmets")',
                        data: { 'id': id },
                        success: function (result) {
                            if (result > 0) {
                                swal({
                                    title: "İşlem Sonucu",
                                    text: "Demirbaş iadesi başarıyla gerçekleşti",
                                    type: "success"
                                }, function () {
                                    location.reload();
                                });
                            }
                        }
                    });
            });
        }




    </script>



}

DmrbTakip/Views/Zimmets/QrReder.cshtml
@{
    ViewBag.Title = "kbul";
    Layout = "~/Views/Shared/_LMaster.cshtml";
}
<link href="~/Qrcode/bootstrap.min.css" rel="stylesheet" />
<style type="text/css">
    .scanner-laser {
        position: absolute;
        margin: 40px;
        height: 30px;
        width: 30px;
    }

    .laser-leftTop {
        top: 0;
        left: 0;
        border-top: solid red 5px;
        border-left: solid red 5px;
    }

    .laser-leftBottom {
        bottom: 0;
        left: 0;
        border-bottom: solid red 5px;
        border-left: solid red 5px;
    }

    .laser-rightTop {
        top: 0;
        right: 0;
        border-top: solid red 5px;
        border-right: solid red 5px;
    }

    .laser-rightBottom {
        bottom: 0;
        right: 0;
        border-bottom: solid red 5px;
        border-right: solid red 5px;
    }
</style>

<div id="QR-Code" class="container" style="width:100%">
    <div class="panel panel-primary">
        <div class="panel-heading" style="display: inline-block;width: 100%; background-color:#333 !important">
            <h4 style="width:50%;float:left;">QR Kod Arama</h4>
            <div style="width:50%;float:right;margin-top: 5px;margin-bottom: 5px;text-align: right;">
                <select id="camera-select" class="form-control" style="visibility:hidden;width: auto;" ></select>
                @*<button id="save" data-toggle="tooltip" title="Image shoot" type="button" class="btn btn-info btn-sm disabled"><span class="glyphicon glyphicon-picture"></span></button>*@
                <button id="play" data-toggle="tooltip" title="Başlat" type="button" class="btn btn-success btn-sm" style="display:none"><span class="glyphicon glyphicon-play"></span></button>
                @*<button id="stop" data-toggle="tooltip" title="Stop" type="button" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-stop"></span></button>*@
                @*<button id="stopAll" data-toggle="tooltip" title="Durdur" type="button" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-stop"></span></button>*@
            </div>
        </div>
        <div class="panel-body">
            <div class="col-md-6" style="text-align: center;">
                <div class="well" style="position: relative;display: inline-block;">
                    <canvas id="webcodecam-canvas"></canvas>
                    <div class="scanner-laser laser-rightBottom" style="opacity: 0.5;"></div>
                    <div class="scanner-laser laser-rightTop" style="opacity: 0.5;"></div>
                    <div class="scanner-laser laser-leftBottom" style="opacity: 0.5;"></div>
                    <div class="scanner-laser laser-leftTop" style="opacity: 0.5;"></div>
                </div>
              
            </div>
            <div class="col-md-6" style="text-align: center;">
                <div id="result" class="thumbnail">
                    @*<div class="well" style="position: relative;visibility: hidden">
                        <img id="scanned-img" src="" width="320" height="240">
                    </div>*@
                    <div class="caption">
                        <h3>Tarama Sonucu</h3>
                        <div id="sonuc">
                            <table class="table">
                                <tr>
                                    <td colspan="2">
                                        <img src="" id="dmbsResim-QR" style="width:250px; height:200px" onerror="this.src='../Resimler/resimyok.jpg'" />
                                        <img src="" id="prsResim-QR" style="width:130px; height:100px; float:right; margin-top: 100px;" onerror="this.src='../Resimler/resimyok.jpg'" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>Yetkili :</td>
                                    <td>
                                        <p id="personel-QR">-</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Bina / Bölüm / Birim-Ofis :</td>
                                    <td><p id="binbolbir-QR">-</p></td>
                                </tr>
                                <tr>
                                    <td>Ürün / Marka / Model :</td>
                                    <td><p id="katmarmod-QR">-</p></td>
                                </tr>
                                <tr>
                                    <td>Demirbaş :</td>
                                    <td><p id="dbadi-QR">-</p></td>
                                </tr>
                                <tr>
                                    <td>Seri No :</td>
                                    <td><p id="seri-QR">-</p></td>
                                </tr>
                                <tr>
                                    <td colspan="2" >
                                        <div class="btn-group" role="group" aria-label="İşlemler">
                                            <button id="cikis" class="btn btn-default">Kapat</button>
                                            <button id="temizle" class="btn btn-warning" style="display:none">Yeni Arama</button>
                                            <button id="git" class="btn btn-danger" style="display:none" data-id="" data-backdrop="">Kayda Git</button> 
                                        </div>                                       
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="panel-footer">
        </div>*@
    </div>
</div>

<script type="text/javascript" src="~/Qrcode/js/filereader.js"></script>
<script type="text/javascript" src="~/Qrcode/js/jquery.js"></script>
<script type="text/javascript" src="~/Qrcode/js/qrcodelib.js"></script>
<script type="text/javascript" src="~/Qrcode/js/webcodecamjquery.js"></script>
<script type="text/javascript" src="~/Qrcode/js/mainjquery.js"></script>
@*<script type="text/javascript" src="~/Qrcode/js/main.js"></script>*@
<script>
    $('#play').click();
    $('#cikis').on('click', function (e) {
        e.preventDefault();
        window.location.href = '@Url.Action("Index","Giris")';
    });
    $('#temizle').on('click', function (e) {
        e.preventDefault();
        location.reload();
    });
    $('#git').on('click', function (e) {
        e.preventDefault();
        var id = $('#git').data('id');
        var yol = $('#git').data('backdrop');      
        window.location.href = '/Zimmets/' + yol + '/' + id;
    });
    $('#webcodecam-canvas').attr('style', 'width:210px;height:170px');
</script>